### ISSUE TITLE
Link Kapost Objects back to Kapost

### ISSUE THREAD

**Issue by level9wizard** [webbuilders-group/silverstripe-kapost-bridge#7]
Within Kapost ingestion process (model admin), while editing a Kapost Object in Silverstripe, the 'Kapost Reference ID' should be linkable back to the Content in Kapost.

**Comment by UndefinedOffset** [comment]
As a side this potentially will require a base url for Kapost be defined in config. Requires some investigating/tinkering with Kapost. If this is the case and it is not defined the text should just not be a link.
